# Generated by Django 4.2.5 on 2023-12-02 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(upload_to='Recruiter profile/')),
                ('companyname', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
