# Generated by Django 4.2.5 on 2023-12-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0003_alter_recruiter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Company logo/')),
                ('company_type', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('est_date', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('company_phn', models.IntegerField()),
                ('company_email', models.EmailField(max_length=254)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.recruiter')),
            ],
        ),
    ]
