# Generated by Django 4.2.5 on 2023-12-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0005_alter_company_est_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyimage', models.ImageField(upload_to='Company gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company_imgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.company')),
                ('recruiter_imgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.recruiter')),
            ],
        ),
    ]
