# Generated by Django 4.2.5 on 2023-12-08 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0006_company_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('salary', models.PositiveIntegerField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('ideal_candidate', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('vaccancy', models.IntegerField()),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('temporary', 'Temporary'), ('remote', 'Remote')], max_length=20)),
                ('startdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('enddate', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('job_compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.company')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.recruiter')),
            ],
        ),
    ]
